test3/QandC/models.py
from django.db import models

class Question(models.Model):
    q = models.TextField(default='')
    date = models.TextField(default='')

class Choice(models.Model):
    que = models.ForeignKey(Question)
    c = models.TextField(default='')

class Answer(models.Model):
    date = models.TextField(default='')
    que = models.ForeignKey(Question)
    ans = models.TextField(default='')

test3/QandC/views.py
#!/usr/bin/python
from django.shortcuts import redirect, render
from QandC.models import Question, Choice,Answer
from django.http import HttpResponse
import operator
import pytz
from django.utils import timezone
import datetime


def home(request):
    if request.method == 'POST' and request.POST.get('q','') == 'q':
        return redirect('/make')
    if request.method == 'POST' and request.POST.get('c','') == 'c':
        return redirect('/answer')
    return render(request, 'home.html')

def make(request):
    if request.method == 'POST' and request.POST.get('send','') == 'send':
        q_text = request.POST['q_text']
        date_time = datetime.datetime.utcnow()
        Question.objects.create(
            q=q_text,
            date = str(date_time)
            )
        q = Question.objects.get(q=q_text)
        return redirect('/make/%d/' %(q.id)) 
    return render(request, 'make.html')

def choice(request, q_id): 
    q = Question.objects.get(pk=q_id)
    if request.method == 'POST' and request.POST.get('send','') == 'send':
        c_text = request.POST['c_text']
        Choice.objects.create(
            que=q,
            c = c_text
            )
        return redirect('/make/%d/' %(q.id))  
    if request.method == 'POST' and request.POST.get('finish','') == 'finish':
        return redirect('/')  
    return render(request, 'cho.html')

def ans(request):
    question = Question.objects.all()
    if request.method == 'POST' and request.POST.get('q','') == 'q':
        return redirect('/answer/%d/' %int(request.POST.get('id_question','')) )
    if request.method == 'POST' and request.POST.get('a','') == 'a':
        return redirect('/show/%d/' %int(request.POST.get('id_question','')) )  
    return render(request, 'ans.html', {'questions': question })

def ansQ(request, q_id):
    q = Question.objects.get(pk=q_id)
    if request.method == 'POST' and request.POST.get('send','') == 'send':
        c_text = request.POST.get('choice','')
        date_time = datetime.datetime.utcnow()
        Answer.objects.create(
            que=q,
            ans = c_text,
            date = str(date_time)
            )
        return redirect('/')
    return render(request, 'ansq.html', {'text_q': q.q , 'question': q })

def show(request, q_id):
    q = Question.objects.get(pk=q_id)
    ans = q.answer_set.all()
    list_ = []
    for a in ans:
        list_.append(a.ans)
    list_count = [[x,list_.count(x)] for x in set(list_)]
    return render(request, 'showans.html', {'text_q': q.q , 'ans': list_count})
    

test3/QandC/templates/ans.html
<html>
    <head>
        <title>Quation</title>
    </head>
    <body>
    <h1>show</h1>
    <table id="id_list_table" border=1>
             {% for question in questions %}
                 <tr>
                 <td>{{ question.date }}</td>
                 <td>{{ question.q }}</td>
                 <td>
                  <FORM method="POST">
                     <INPUT Type="submit" VALUE="question" id="button_q" >      
                     <INPUT Type = "hidden" value ="q" name = 'q'>
                     <INPUT Type = "hidden" value ="{{ question.id }}" name = 'id_question'>
                     {% csrf_token %}
                 </FORM>
                 </td>
                 <td>
                  <FORM method="POST">
                     <INPUT Type="submit" VALUE="answer" id="button_a" >      
                     <INPUT Type = "hidden" value ="a" name = 'a'>
                     <INPUT Type = "hidden" value ="{{ question.id }}" name = 'id_question'>
                     {% csrf_token %}
                 </FORM>
                 </td>
                 <tr>          
            {% endfor %}
        </table>
    </body>
</html>

test3/QandC/templates/ansq.html
<html>
    <head>
        <title>answer</title>
    </head>
    <body>
        <h1>answer</h1>  
        {{text_q}}
        <FORM method="POST" >
        {% for c in question.choice_set.all %}
        <INPUT TYPE="radio" NAME="choice" id="choice" VALUE="{{c.c}}">{{c.c}}
        <br>
        {% endfor %}
        <INPUT Type="submit" VALUE="enter" id="button" >
        <INPUT Type = "hidden" value ="send" name = 'send'>
        {% csrf_token %}
        </FROM>
        </body>
</html>

test3/QandC/templates/cho.html
<html>
    <head>
        <title>Q&C make</title>
    </head>
    <body>
        <h1></h1> 
      <FORM method="POST">
            คำตอบ
           <br>
           <input name="c_text" id="c_new"/>
           <br>
            <INPUT Type="submit" VALUE="enter" id="button_en" >
            <INPUT Type = "hidden" value ="send" name = 'send'>
            {% csrf_token %}
           <br>
       </FORM> 
        <FORM method="POST">
            <INPUT Type="submit" VALUE="จบ" id="button_f" >
            <INPUT Type = "hidden" value ="finish" name = 'finish'>
            {% csrf_token %}
       </FORM> 
    </body>
</html>

test3/QandC/templates/home.html
<html>
    <head>
        <title>Q&C</title>
    </head>
    <body>
        <h1>from</h1> 
     <FORM method="POST">
            <INPUT Type="submit" VALUE="สร้างคำถาม" id="button_q" >
            <INPUT Type = "hidden" value ="q" name = 'q'>
            {% csrf_token %}
       </FORM> 
      <FORM method="POST">
            <INPUT Type="submit" VALUE="ตอบคำถาม" id="button_c" >
            <INPUT Type = "hidden" value ="c" name = 'c'>
            {% csrf_token %}
       </FORM> 
    </body>
</html>

test3/QandC/templates/make.html
<html>
    <head>
        <title>Q&C make</title>
    </head>
    <body>
        <h1>Question</h1> 
      <FORM method="POST">
                 คำถาม
           <br>
           <input name="q_text" id="q_new"/>
           <br>
            <INPUT Type="submit" VALUE="enter" id="button_en" >
            <INPUT Type = "hidden" value ="send" name = 'send'>
            {% csrf_token %}
       </FORM> 
    </body>
</html>